[project]
name = "ukfi-analytics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "arunsankarask", email = "arunsankar888@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "quantlib>=1.43",
]

[project.scripts]
ukfi-analytics = "ukfi_analytics:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "hypothesis>=6.168.0",
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.7",
]
